name: My Action

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked, review_requested, review_request_removed, labeled, unlabeled, assigned, unassigned, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked, review_requested, review_request_removed, labeled, unlabeled, assigned, unassigned]

permissions:
  issues: write
  pages: write

jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/new-org-12345345/clean/pages \
            -d '{"source":{"branch":"main","path":"/"}}'


